---

- hosts: all
  gather_facts: no

  tasks:
    - name: create env file
      template:
        src: templates/env.j2
        dest: /.env

    - community.docker.docker_container:
        name: redmine-example-app
        image: redmine:5.0.2
        env_file: /.env
        restart_policy: always
        ports:
          - 80:3000
